version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: oneeats-postgres-dev
    environment:
      POSTGRES_DB: oneeats_dev
      POSTGRES_USER: oneeats_user
      POSTGRES_PASSWORD: oneeats_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - oneeats-network

  postgres-test:
    image: postgres:15
    container_name: oneeats-postgres-test
    environment:
      POSTGRES_DB: oneeats_test
      POSTGRES_USER: oneeats_test_user
      POSTGRES_PASSWORD: oneeats_test_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - oneeats-network
    tmpfs:
      - /var/lib/postgresql/data:noexec,nosuid,size=200m

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: oneeats-pgadmin-dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@oneeats.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
      - postgres-test
    networks:
      - oneeats-network

volumes:
  postgres_data:
  postgres_test_data:

networks:
  oneeats-network:
    driver: bridge