quarkus:
  # Configuration production optimisée
  application:
    name: OneEats Backend - Production
  
  http:
    port: ${PORT:8080}
    cors:
      ~: true
      origins: ${CORS_ORIGINS:https://oneeats.com}
  
  # Base de données production
  datasource:
    jdbc:
      url: ${DATABASE_URL}
      max-size: 50
      min-size: 10
      acquisition-timeout: 10s
      leak-detection-interval: 30s
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  
  hibernate-orm:
    database:
      generation: validate
    log:
      sql: false
    statistics: false
    metrics:
      enabled: true
  
  # Logs production
  log:
    level: INFO
    category:
      "com.oneeats": INFO
      "org.hibernate.SQL": WARN
    console:
      enable: true
      json: true  # Pour les systèmes de logs centralisés
  
  # Sécurité production
  security:
    users:
      embedded:
        enabled: false
  
  # Métriques et monitoring
  micrometer:
    export:
      prometheus:
        enabled: true
        path: /actuator/prometheus
  
  smallrye-health:
    ui:
      enable: false  # Désactiver l'UI en production
  
  # Package natif pour de meilleures performances
  package:
    type: native
    
  native:
    resources:
      includes:
        - "*.yml"
        - "*.properties"
        - "*.sql"

# Configuration production OneEats
oneeats:
  business:
    notification:
      enabled: true
      email-enabled: true
      sms-enabled: true
  
  api:
    rate-limit:
      enabled: true
      requests-per-minute: 120  # Plus élevé en production
  
  security:
    jwt:
      issuer: ${JWT_ISSUER}
      audience: ${JWT_AUDIENCE}