# Harmonize Markdown Workflow
name: "harmonize-markdown"
description: "Normalise la documentation Markdown (titres, TOC, style) sur le périmètre actif du projet."
author: "Custom"

# Critical variables
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated
output_folder: "{config_source}:implementation_artifacts"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/harmonize-markdown"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Scope configuration
scope:
  includes:
    - "docs/**/*.md"
    - "README.md"
  excludes:
    - "docs/archive/**"
    - "docs/adr/**"

# Behavior
standalone: true

